-- SAF - Schema inicial para Supabase/PostgreSQL
-- Execute este script no SQL Editor do Supabase.

begin;

-- Necessario para gen_random_uuid()
create extension if not exists pgcrypto;

-- =========================================================
-- Tabela: usuarios
-- Perfil de acesso do sistema, vinculado ao auth.users do Supabase
-- =========================================================
create table if not exists public.usuarios (
  id uuid primary key references auth.users(id) on delete cascade,
  nome text not null,
  email text not null unique,
  perfil text not null check (perfil in ('SOLICITANTE', 'CCM', 'ADMIN')),
  ativo boolean not null default true,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

-- =========================================================
-- Tabelas de cache para Search Help
-- =========================================================
create table if not exists public.locais_instalacao (
  id bigint generated by default as identity primary key,
  codigo text not null unique,
  descricao text not null,
  ativo boolean not null default true,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create table if not exists public.equipamentos (
  id bigint generated by default as identity primary key,
  codigo text not null unique,
  descricao text not null,
  local_instalacao_id bigint references public.locais_instalacao(id) on update cascade on delete set null,
  ativo boolean not null default true,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create table if not exists public.sintomas_catalogo (
  id bigint generated by default as identity primary key,
  codigo text not null unique,
  descricao text not null,
  categoria text,
  ativo boolean not null default true,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

-- =========================================================
-- Tabela: saf_solicitacoes
-- Dados da falha preenchidos pelo solicitante
-- =========================================================
create table if not exists public.saf_solicitacoes (
  id uuid primary key default gen_random_uuid(),
  solicitante_id uuid not null references public.usuarios(id) on update cascade on delete restrict,
  local_instalacao_id bigint references public.locais_instalacao(id) on update cascade on delete set null,
  equipamento_id bigint references public.equipamentos(id) on update cascade on delete set null,
  sintoma_id bigint references public.sintomas_catalogo(id) on update cascade on delete set null,
  titulo text not null,
  descricao_falha text not null,
  url_foto text,
  prioridade text not null default 'MEDIA' check (prioridade in ('BAIXA', 'MEDIA', 'ALTA', 'CRITICA')),
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

-- =========================================================
-- Tabela: saf_controle_ccm (workflow 1:1)
-- Uma linha para cada solicitacao
-- =========================================================
create table if not exists public.saf_controle_ccm (
  solicitacao_id uuid primary key references public.saf_solicitacoes(id) on delete cascade,
  status text not null default 'ABERTA' check (
    status in ('ABERTA', 'EM_ANALISE', 'DEVOLVIDA', 'APROVADA', 'CANCELADA')
  ),
  motivo_devolucao text,
  motivo_cancelamento text,
  avaliado_por uuid references public.usuarios(id) on update cascade on delete set null,
  data_avaliacao timestamptz,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  constraint chk_motivo_devolucao
    check (
      (status <> 'DEVOLVIDA')
      or (status = 'DEVOLVIDA' and motivo_devolucao is not null and length(trim(motivo_devolucao)) > 0)
    )
);

-- =========================================================
-- Tabela: saf_integracao_sap (1:1 com solicitacao)
-- Isola dados de integracao com SAP
-- =========================================================
create table if not exists public.saf_integracao_sap (
  solicitacao_id uuid primary key references public.saf_solicitacoes(id) on delete cascade,
  qmnum text unique,
  aufnr text unique,
  status_integracao text not null default 'PENDENTE' check (
    status_integracao in ('PENDENTE', 'SUCESSO', 'ERRO', 'CANCELAMENTO_PENDENTE', 'CANCELAMENTO_ERRO')
  ),
  payload_envio jsonb,
  payload_resposta jsonb,
  ultima_tentativa_em timestamptz,
  mensagem_erro text,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

-- =========================================================
-- Tabela: logs_auditoria
-- Rastreabilidade (LGPD)
-- =========================================================
create table if not exists public.logs_auditoria (
  id bigint generated by default as identity primary key,
  usuario_id uuid references public.usuarios(id) on update cascade on delete set null,
  acao text not null,
  entidade text not null,
  entidade_id text,
  dados_antes jsonb,
  dados_depois jsonb,
  ip_origem inet,
  user_agent text,
  criado_em timestamptz not null default now()
);

-- =========================================================
-- Tabela: frotas_trens
-- Relaciona series/prefixos de trens a um local de instalacao
-- =========================================================
create table if not exists public.frotas_trens (
  id uuid not null default gen_random_uuid(),
  codigo_local text not null,
  serie_trem character varying(10) not null,
  prefixo_trem character varying(10),
  status character varying(20) default 'operacional',
  criado_em timestamptz default now(),
  atualizado_em timestamptz default now(),
  constraint frotas_trens_pkey primary key (id),
  constraint fk_local_instalacao
    foreign key (codigo_local)
    references public.locais_instalacao(codigo)
    on update cascade
    on delete cascade
);

-- =========================================================
-- Tabela: trechos_vias
-- Cadastro de trechos por linha e codigo de local
-- =========================================================
create table if not exists public.trechos_vias (
  id uuid not null default gen_random_uuid(),
  codigo_local text not null,
  linha character varying(2) not null,
  estacao_origem character varying(100) not null,
  estacao_destino character varying(100) not null,
  descricao text not null,
  criado_em timestamptz default now(),
  constraint trechos_vias_pkey primary key (id),
  constraint trechos_vias_codigo_local_key unique (codigo_local)
);

-- =========================================================
-- Indices para performance
-- =========================================================
create index if not exists idx_usuarios_perfil on public.usuarios(perfil);

create index if not exists idx_frotas_codigo_local
  on public.frotas_trens(codigo_local);

create index if not exists idx_frotas_serie
  on public.frotas_trens(serie_trem);

create index if not exists idx_trechos_linha
  on public.trechos_vias(linha);

create index if not exists idx_trechos_codigo
  on public.trechos_vias(codigo_local);

create index if not exists idx_equipamentos_local_instalacao_id
  on public.equipamentos(local_instalacao_id);

create index if not exists idx_saf_solicitacoes_solicitante_id
  on public.saf_solicitacoes(solicitante_id);

create index if not exists idx_saf_solicitacoes_local_instalacao_id
  on public.saf_solicitacoes(local_instalacao_id);

create index if not exists idx_saf_solicitacoes_equipamento_id
  on public.saf_solicitacoes(equipamento_id);

create index if not exists idx_saf_solicitacoes_sintoma_id
  on public.saf_solicitacoes(sintoma_id);

create index if not exists idx_saf_controle_ccm_status
  on public.saf_controle_ccm(status);

create index if not exists idx_saf_integracao_sap_status
  on public.saf_integracao_sap(status_integracao);

create index if not exists idx_logs_auditoria_usuario_id
  on public.logs_auditoria(usuario_id);

create index if not exists idx_logs_auditoria_entidade_entidade_id
  on public.logs_auditoria(entidade, entidade_id);

create index if not exists idx_logs_auditoria_criado_em
  on public.logs_auditoria(criado_em desc);

-- =========================================================
-- Trigger generico para manter atualizado_em
-- =========================================================
create or replace function public.fn_set_atualizado_em()
returns trigger
language plpgsql
as $$
begin
  new.atualizado_em = now();
  return new;
end;
$$;

create trigger trg_usuarios_set_atualizado_em
before update on public.usuarios
for each row execute function public.fn_set_atualizado_em();

create trigger trg_locais_instalacao_set_atualizado_em
before update on public.locais_instalacao
for each row execute function public.fn_set_atualizado_em();

create trigger trg_equipamentos_set_atualizado_em
before update on public.equipamentos
for each row execute function public.fn_set_atualizado_em();

create trigger trg_sintomas_catalogo_set_atualizado_em
before update on public.sintomas_catalogo
for each row execute function public.fn_set_atualizado_em();

create trigger trg_frotas_trens_set_atualizado_em
before update on public.frotas_trens
for each row execute function public.fn_set_atualizado_em();

create trigger trg_saf_solicitacoes_set_atualizado_em
before update on public.saf_solicitacoes
for each row execute function public.fn_set_atualizado_em();

create trigger trg_saf_controle_ccm_set_atualizado_em
before update on public.saf_controle_ccm
for each row execute function public.fn_set_atualizado_em();

create trigger trg_saf_integracao_sap_set_atualizado_em
before update on public.saf_integracao_sap
for each row execute function public.fn_set_atualizado_em();

commit;
